In [1]:
import sys
sys.path.append('..')
from lime import lime_tabular
import numpy as np
from sklearn.utils import check_random_state

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()
boston.data.shape

(506, 13)

In [3]:
from lime import AHC
ahc = AHC.Hierarchical(k=4)
ahc.fit(boston.data)
print(ahc.labels)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 

In [ ]:
np.array([[1,2,3], [2,3,4]]) - np.array([1,2,2])

In [ ]:
for i in np.array([[1,2,3], [2,3,4]]):
    print(i)

In [ ]:
np.array(ahc.labels).reshape(-1,1)

In [4]:
from lime.KNN import KNN

knn = KNN(np.hstack((boston.data[1:], np.array(ahc.labels[1:]).reshape(-1,1))), boston.data[0], k=5)
knn.fit()
len(knn.result)

363

In [ ]:
np.array([1,2]).shape

In [25]:
a = np.array([[1, 2, 3], [2,3,4]])
a[[0]][:,[1, 2]]

array([[2, 3]])

In [7]:
np.concatenate([np.array([1,2]), np.array([0])])

array([1, 2, 0])

In [27]:
a = np.array([1,2,3])
a[[1,2]]

array([2, 3])

In [1]:
import numpy as np
a = np.array([[1], [2], [3]])
3 - a

array([[2],
       [1],
       [0]])

In [4]:
np.array([[0.1, 0.2]]) + np.array([0.1, 0.2])

array([[0.2, 0.4]])

In [2]:
np.random.uniform(-1,0,10)

array([-0.83852094, -0.59132486, -0.68198657, -0.54189455, -0.56331811,
       -0.68566663, -0.44469264, -0.48261089, -0.18656119, -0.20228627])